import type { LearningPath } from '../types';

/**
 * Curriculum is code-owned on purpose: replacing a video in a later release
 * should reach existing users without rewriting their personal progress.
 * Keep lesson ids stable when swapping resources for the same learning goal.
 */
export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'business',
    title: 'Start & Grow a Business',
    subtitle: 'From zero to customers, product-market fit, growth and operating a real business.',
    stages: [
      {
        id: 'business-foundations',
        title: 'Stage 1 · Foundations',
        description: 'Problems, customers and the basic model of a business.',
        lessons: [
          {
            id: 'business-ideas-01',
            title: 'How to Get and Evaluate Startup Ideas',
            source: 'Y Combinator',
            type: 'video',
            priority: 'core',
            durationMinutes: 33,
            url: 'https://www.youtube.com/watch?v=Th8JoIan4dg',
          },
          {
            id: 'business-model-canvas-01',
            title: 'Business Model Canvas Explained',
            source: 'Strategyzer',
            type: 'video',
            priority: 'core',
            durationMinutes: 3,
            url: 'https://www.youtube.com/watch?v=QoAOzMTLP5s',
          },
          {
            id: 'business-value-proposition-01',
            title: 'Value Proposition Canvas Explained',
            source: 'Strategyzer',
            type: 'video',
            priority: 'core',
            durationMinutes: 3,
            url: 'https://www.youtube.com/watch?v=ReM1uqmVfP0',
          },
          {
            id: 'business-user-interviews-01',
            title: 'How to Talk to Users',
            source: 'Y Combinator',
            type: 'video',
            priority: 'core',
            durationMinutes: 31,
            url: 'https://www.youtube.com/watch?v=z1iF1c8w5Lg',
          },
        ],
      },
      {
        id: 'business-market',
        title: 'Stage 2 · Product & Market',
        description: 'Get real customers, launch, and learn what product-market fit feels like.',
        lessons: [
          {
            id: 'business-first-customers-01',
            title: 'How to Get Your First Customers',
            source: 'Y Combinator',
            type: 'video',
            priority: 'core',
            durationMinutes: 28,
            url: 'https://www.youtube.com/watch?v=hyYCn_kAngI',
          },
          {
            id: 'business-launch-01',
            title: 'How to Launch (Again and Again)',
            source: 'Y Combinator',
            type: 'video',
            priority: 'recommended',
            durationMinutes: 25,
            url: 'https://www.youtube.com/watch?v=3xU050kMbHM',
          },
          {
            id: 'business-pmf-01',
            title: 'How to Find Product Market Fit',
            source: 'Stanford · Peter Reinhardt',
            type: 'case-study',
            priority: 'core',
            durationMinutes: 48,
            url: 'https://www.youtube.com/watch?v=_6pl5GG8RQ4',
          },
        ],
      },
      {
        id: 'business-growth',
        title: 'Stage 3 · Funnel, Metrics & Growth',
        description: 'Understand where customers are in the journey and what numbers matter.',
        lessons: [
          {
            id: 'business-funnel-01',
            title: 'TOFU / MOFU / BOFU — The 3 Funnel Stages',
            source: 'YouTube',
            type: 'video',
            priority: 'core',
            durationMinutes: 10,
            url: 'https://www.youtube.com/watch?v=02cqK-CR9ws',
          },
          {
            id: 'business-aarrr-01',
            title: 'Startup Metrics for Pirates: AARRR',
            source: 'Dave McClure',
            type: 'video',
            priority: 'core',
            durationMinutes: 5,
            url: 'https://www.youtube.com/watch?v=irjgfW0BIrw',
          },
          {
            id: 'business-small-startup-product-01',
            title: 'How To Build Product As A Small Startup',
            source: 'Y Combinator · Michael Seibel',
            type: 'video',
            priority: 'core',
            durationMinutes: 29,
            url: 'https://www.youtube.com/watch?v=kzVvjKLdAbk',
          },
        ],
      },
    ],
  },
  {
    id: 'ai-agents',
    title: 'Great & Reliable AI Agent Team',
    subtitle: 'Build agents that use tools, work together, can be evaluated, and are safe enough for real work.',
    stages: [
      {
        id: 'agents-foundations',
        title: 'Stage 1 · Agent Fundamentals',
        description: 'What an agent is, when to use one, and the core mental models.',
        lessons: [
          {
            id: 'agents-what-are-agents-01',
            title: 'What are AI Agents?',
            source: 'IBM Technology',
            type: 'video',
            priority: 'core',
            durationMinutes: 11,
            url: 'https://www.youtube.com/watch?v=F8NKVhkZZWI',
          },
          {
            id: 'agents-effective-agents-01',
            title: 'How to Build Effective AI Agents',
            source: 'Anthropic',
            type: 'video',
            priority: 'core',
            durationMinutes: 40,
            url: 'https://www.youtube.com/watch?v=LP5OCa20Zpg',
          },
          {
            id: 'agents-guides-overview-01',
            title: "Google, Anthropic & OpenAI's Guides to AI Agents",
            source: 'YouTube',
            type: 'video',
            priority: 'recommended',
            durationMinutes: 16,
            url: 'https://www.youtube.com/watch?v=TlbcAphLGSc',
          },
        ],
      },
      {
        id: 'agents-architecture',
        title: 'Stage 2 · Build & Architecture',
        description: 'Tools, MCP, agent loops and multi-agent patterns.',
        lessons: [
          {
            id: 'agents-sdk-build-hour-01',
            title: 'Build Hour: Agents SDK',
            source: 'OpenAI',
            type: 'video',
            priority: 'core',
            durationMinutes: 48,
            url: 'https://www.youtube.com/watch?v=tK32trvj_b4',
          },
          {
            id: 'agents-multi-agent-architecture-01',
            title: 'Conceptual Guide: Multi-Agent Architectures',
            source: 'LangChain',
            type: 'video',
            priority: 'core',
            durationMinutes: 49,
            url: 'https://www.youtube.com/watch?v=4nZl32FwU-o',
          },
          {
            id: 'agents-choose-architecture-01',
            title: 'Choosing the Right Multi-Agent Architecture',
            source: 'LangChain',
            type: 'video',
            priority: 'core',
            durationMinutes: 35,
            url: 'https://www.youtube.com/watch?v=fqvbxkgU6vE',
          },
        ],
      },
      {
        id: 'agents-reliability',
        title: 'Stage 3 · Reliability & Security',
        description: 'Trace what happened, evaluate behavior, and design for failure.',
        lessons: [
          {
            id: 'agents-observability-evals-01',
            title: 'Observability and Evals for AI Agents',
            source: 'LangChain',
            type: 'video',
            priority: 'core',
            durationMinutes: 45,
            url: 'https://www.youtube.com/watch?v=FDVdLrloFOw',
          },
          {
            id: 'agents-security-risks-01',
            title: 'Top 10 Security Risks in AI Agents Explained',
            source: 'IBM Technology',
            type: 'video',
            priority: 'core',
            durationMinutes: 16,
            url: 'https://www.youtube.com/watch?v=soFWS8NBcSU',
          },
        ],
      },
    ],
  },
  {
    id: 'negotiation',
    title: 'Business Negotiation Strategy',
    subtitle: 'Prepare leverage, uncover interests, structure deals and know when to walk away.',
    stages: [
      {
        id: 'negotiation-foundations',
        title: 'Stage 1 · Fundamentals',
        description: 'A principled framework for preparing and solving negotiation problems.',
        lessons: [
          {
            id: 'negotiation-neale-01',
            title: 'Negotiation: Getting What You Want',
            source: 'Stanford GSB · Margaret Neale',
            type: 'video',
            priority: 'core',
            durationMinutes: 54,
            url: 'https://www.youtube.com/watch?v=MXFpOWDAhvM',
          },
          {
            id: 'negotiation-ury-01',
            title: 'The Walk from “No” to “Yes”',
            source: 'William Ury',
            type: 'video',
            priority: 'core',
            durationMinutes: 19,
            url: 'https://www.youtube.com/watch?v=Hc6yi_FtoNo',
          },
        ],
      },
      {
        id: 'negotiation-tactical',
        title: 'Stage 2 · Tactical Negotiation',
        description: 'Listening, tactical empathy, information and difficult conversations.',
        lessons: [
          {
            id: 'negotiation-voss-01',
            title: 'Never Split the Difference',
            source: 'Talks at Google · Chris Voss',
            type: 'video',
            priority: 'core',
            durationMinutes: 51,
            url: 'https://www.youtube.com/watch?v=guZa7mQV1l0',
          },
          {
            id: 'negotiation-diamond-01',
            title: 'The Art of Negotiation',
            source: 'Talks at Google · Stuart Diamond',
            type: 'video',
            priority: 'recommended',
            durationMinutes: 66,
            url: 'https://www.youtube.com/watch?v=2QtZ-vObJrk',
          },
        ],
      },
      {
        id: 'negotiation-deals',
        title: 'Stage 3 · Deal Structure',
        description: 'Use leverage and structure the whole package rather than arguing over one number.',
        lessons: [
          {
            id: 'negotiation-malhotra-01',
            title: 'How to Negotiate Your Job Offer',
            source: 'Harvard Business School · Deepak Malhotra',
            type: 'case-study',
            priority: 'core',
            durationMinutes: 65,
            url: 'https://www.youtube.com/watch?v=km2Hd_xgo9Q',
          },
        ],
      },
    ],
  },
];
